MARKDOWN_START = """
## Glyph_E1
Autogenerated with [rego-glyph](https://github.com/llgava/regolith-filters/tree/main/rego-glyph) filter by `Leonardo '_Fyat' Gava`

"""

MARKDOWN_END = """

## Support
Found a issue?<br />
Open it [here](https://github.com/llgava/regolith-filters/issues) so I can check and fix if needed.
"""
